apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: daprps
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: daprps
data:
  init-db.sql: |
    -- Create databases for our services
    CREATE DATABASE productdb OWNER postgres;
    CREATE DATABASE paymentdb OWNER postgres;

    -- Grant privileges
    GRANT ALL PRIVILEGES ON DATABASE productdb TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE paymentdb TO postgres; 