apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: daprps-prod

resources:
  - ../../base
  - namespace.yaml

patchesStrategicMerge:
  - resource-patch.yaml

commonLabels:
  environment: production
  app.kubernetes.io/environment: production 