apiVersion: v1
kind: Service
metadata:
  name: gingateway
  labels:
    app: gingateway
spec:
  type: ClusterIP
  selector:
    app: gingateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 