apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: daprps
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
  - name: zookeeper
    port: 2181
    targetPort: 2181
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: daprps
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
  type: ClusterIP 