apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka:29092"
    - name: authRequired
      value: "false"
    - name: publishRetryAttempts
      value: "3"
    - name: publishRetryInterval
      value: "100ms"
    - name: consumeRetryAttempts
      value: "3"
    - name: consumeRetryInterval
      value: "100ms"
    - name: maxMessageBytes
      value: "1024"
    - name: initialOffset
      value: "newest"
    - name: consumerGroup
      value: "dapr-consumer-group" 