apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: daprps-dev

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: postgres-patch.yaml
    target:
      kind: Deployment
      name: postgres
  - path: redis-patch.yaml
    target:
      kind: Deployment
      name: redis
  - path: kafka-patch.yaml
    target:
      kind: Deployment
      name: kafka

commonLabels:
  environment: development
  app.kubernetes.io/environment: development 